packageIdentifier: Alacritty.Alacritty
manifestPath: manifests/a/Alacritty/Alacritty

checkver:
  type: github
  repo: alacritty/alacritty

installerUrlTemplate: "https://github.com/alacritty/alacritty/releases/download/v{version}/Alacritty-v{version}-installer.msi"
