packageIdentifier: Alacritty.Alacritty
# Path structure: manifests/{first-letter}/{publisher}/{package}
# Example: https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/Alacritty/Alacritty
manifestPath: manifests/a/Alacritty/Alacritty

checkver:
  type: github
  repo: alacritty/alacritty
  regex: "v?([\\d\\.]+)"

updateMetadata:
  - ReleaseNotes
  - ReleaseNotesUrl

# Alacritty installer URL from GitHub releases
# Uses MSI installer format: Alacritty-v{version}-installer.msi
installerUrlTemplate: "https://github.com/alacritty/alacritty/releases/download/v{version}/Alacritty-v{version}-installer.msi"
