packageIdentifier: Microsoft.Sysinternals.Suite
manifestPath: manifests/m/Microsoft/Sysinternals/Suite

checkver:
  type: script
  script: |
    $response = Invoke-WebRequest -Uri "https://raw.githubusercontent.com/MicrosoftDocs/sysinternals/live/sysinternals/downloads/sysinternals-suite.md" -UseBasicParsing
    $content = $response.Content
    
    if ($content -match 'ms\.date:\s*(\d{2})/(\d{2})/(\d{4})') {
      Write-Output "$($Matches[1])/$($Matches[2])/$($Matches[3])"
    }
  regex: "(\\d{2})/(\\d{2})/(\\d{4})"
  replace: "${3}-${1}-${2}"

installerUrlTemplate:
  x64: "https://download.sysinternals.com/files/SysinternalsSuite.zip"
  arm64: "https://download.sysinternals.com/files/SysinternalsSuite-ARM64.zip"
