packageIdentifier: Microsoft.GameInput
manifestPath: manifests/m/Microsoft/GameInput

checkver:
  type: github
  repo: microsoftconnect/GameInput

installerUrlTemplate: "https://github.com/microsoftconnect/GameInput/releases/download/v{version}/GameInputRedist.msi"
