packageIdentifier: Microsoft.GameInput
# Path structure: manifests/{first-letter}/{publisher}/{package}
# Example: https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/GameInput
# Raw manifest reference: https://raw.githubusercontent.com/microsoft/winget-pkgs/master/manifests/m/Microsoft/GameInput/3.0.26100.6154/Microsoft.GameInput.installer.yaml
manifestPath: manifests/m/Microsoft/GameInput

checkver:
  type: script
  script: |
    # Get latest stable release from GitHub API
    # https://github.com/microsoftconnect/GameInput
    $response = Invoke-RestMethod -Uri "https://api.github.com/repos/microsoftconnect/GameInput/releases/latest"
    if ($response.tag_name) {
      # Remove 'v' prefix (e.g., v3.0.26100.6154 -> 3.0.26100.6154)
      $version = $response.tag_name -replace '^v', ''
      Write-Output $version
    }
  regex: "([\\d\\.]+)"

# GameInput installer URL from GitHub releases
# Tag format: v3.0.26100.6154, installer filename: GameInputRedist.msi
installerUrlTemplate: "https://github.com/microsoftconnect/GameInput/releases/download/v{version}/GameInputRedist.msi"
