checkver:
  type: github
  repo: rclone/rclone


installerUrlTemplate:
  x86: "https://github.com/rclone/rclone/releases/download/v{version}/rclone-v{version}-windows-386.zip"
  x64: "https://github.com/rclone/rclone/releases/download/v{version}/rclone-v{version}-windows-amd64.zip"
  arm64: "https://github.com/rclone/rclone/releases/download/v{version}/rclone-v{version}-windows-arm64.zip"
