packageIdentifier: Rclone.Rclone
# Path structure: manifests/{first-letter}/{publisher}/{package}
# Example: https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Rclone/Rclone
# Raw manifest reference: https://raw.githubusercontent.com/microsoft/winget-pkgs/master/manifests/r/Rclone/Rclone/1.71.2/Rclone.Rclone.installer.yaml
manifestPath: manifests/r/Rclone/Rclone

checkver:
  type: script
  script: |
    # Get latest release from GitHub API
    # https://github.com/rclone/rclone
    $response = Invoke-RestMethod -Uri "https://api.github.com/repos/rclone/rclone/releases/latest"
    if ($response.tag_name) {
      # Tag format: v1.71.2 (with 'v' prefix)
      $version = $response.tag_name -replace '^v', ''
      $releaseNotes = $response.body
      $releaseNotesUrl = $response.html_url
      
      # Output format: version|releaseNotesUrl|releaseNotes
      Write-Output "$version|$releaseNotesUrl|$releaseNotes"
    }
  regex: "(?P<version>[\\d\\.]+)\\|(?P<releaseNotesUrl>[^\\|]+)\\|(?P<releaseNotes>.*)"

# Rclone installer URLs from GitHub releases
# Format: rclone-v{version}-windows-{arch}.zip
installerUrlTemplate:
  x86: "https://github.com/rclone/rclone/releases/download/v{version}/rclone-v{version}-windows-386.zip"
  x64: "https://github.com/rclone/rclone/releases/download/v{version}/rclone-v{version}-windows-amd64.zip"
  arm64: "https://github.com/rclone/rclone/releases/download/v{version}/rclone-v{version}-windows-arm64.zip"
