packageIdentifier: Roblox.Roblox
manifestPath: manifests/r/Roblox/Roblox
templateVersion: "1.6.2.6660608"  # Template from commit f4b71b38553b3f3ec6103d93dee738568c5484f0
templateCommit: "f4b71b38553b3f3ec6103d93dee738568c5484f0"  # Fallback when no versions exist on master
checkver:
  type: script
  script: |
    $response = Invoke-WebRequest -Uri "https://clientsettingscdn.roblox.com/v1/client-version/WindowsPlayer" -UseBasicParsing
    $json = $response.Content | ConvertFrom-Json
    
    $version = $json.version
    $clientVersionUpload = $json.clientVersionUpload
    
    if ([string]::IsNullOrEmpty($version) -or [string]::IsNullOrEmpty($clientVersionUpload)) {
        Write-Error "Failed to get version or clientVersionUpload"
        exit 1
    }
    
    # Output in format: version|clientVersionUpload
    Write-Output "$version|$clientVersionUpload"
  regex: "(?P<version>[\\d\\.]+)\\|(?P<clientVersionUpload>version-[a-f0-9]+)"
installerUrlTemplate: "https://setup.rbxcdn.com/{clientVersionUpload}-RobloxPlayerInstaller.exe"
