packageIdentifier: RustDesk.RustDesk
# Path structure: manifests/{first-letter}/{publisher}/{package}
# Example: https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/RustDesk/RustDesk
# Raw manifest reference: https://raw.githubusercontent.com/microsoft/winget-pkgs/master/manifests/r/RustDesk/RustDesk/1.3.2/RustDesk.RustDesk.installer.yaml
manifestPath: manifests/r/RustDesk/RustDesk

# GitHub-based checkver
checkver:
  type: github
  repo: rustdesk/rustdesk

# Metadata to fetch from GitHub
updateMetadata:
  - ReleaseNotes
  - ReleaseNotesUrl

# RustDesk installer URLs from GitHub releases
# x86 uses -x86-sciter.exe, x64 uses -x86_64.exe
installerUrlTemplate:
  x86: "https://github.com/rustdesk/rustdesk/releases/download/{version}/rustdesk-{version}-x86-sciter.exe"
  x64: "https://github.com/rustdesk/rustdesk/releases/download/{version}/rustdesk-{version}-x86_64.exe"
