packageIdentifier: Stremio.StremioService
manifestPath: manifests/s/Stremio/StremioService

checkver:
  type: github
  repo: Stremio/stremio-service

installerUrlTemplate: "https://github.com/Stremio/stremio-service/releases/download/v{version}/StremioServiceSetup.exe"
