packageIdentifier: Stremio.StremioService
# Path structure: manifests/{first-letter}/{publisher}/{package}
# Example: https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/Stremio/StremioService
manifestPath: manifests/s/Stremio/StremioService

checkver:
  type: github
  repo: Stremio/stremio-service
  regex: "v?([\\d\\.]+)"

# Installer URL template from GitHub releases
# Example: https://github.com/Stremio/stremio-service/releases/download/v0.1.14/StremioServiceSetup.exe
installerUrlTemplate: "https://github.com/Stremio/stremio-service/releases/download/v{version}/StremioServiceSetup.exe"
